export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const SET_TODO_LIST_VISIBILITY_FILTER = 'SET_TODO_LIST_VISIBILITY_FILTER';

export const SHOW_ALL_TODO = 'SHOW_ALL_TODO';
export const SHOW_ACTIVE_TODO = 'SHOW_ACTIVE_TODO';
export const SHOW_COMPLETED_TODO = 'SHOW_COMPLETED_TODO';
